# Modules
":floppy_disk: amazon-issued-cert":
- changed-files:
  - any-glob-to-any-file:
    - modules/amazon-issued-cert/**/*

":floppy_disk: imported-cert":
- changed-files:
  - any-glob-to-any-file:
    - modules/imported-cert/**/*

":floppy_disk: private-ca-issued-cert":
- changed-files:
  - any-glob-to-any-file:
    - modules/private-ca-issued-cert/**/*
